### ISSUE TITLE
MalformedXML error

### ISSUE THREAD

**Issue by jaydeepw** [jgilfelt/android-simpl3r#4]
When I try to upload a file using simpl3r, I get this exception.
I tried a quick google search to fix, but didnt work.

05-25 21:12:31.940: W/System.err(21275): Status Code: 400, AWS Service: Amazon S3, AWS Request ID: 25950685FA4A7BA0, AWS Error Code: MalformedXML, AWS Error Message: The XML you provided was not well-formed or did not validate against our published schema, S3 Extended Request ID: lFNEIr7bNf2wmQvoG1wztfVqTCHgRTfsXL8GQAXLWwEs7ZqMdaLdRwcXVfmz7iPm
05-25 21:12:31.940: W/System.err(21275):    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(Unknown Source)
05-25 21:12:31.940: W/System.err(21275):    at com.amazonaws.http.AmazonHttpClient.executeHelper(Unknown Source)
05-25 21:12:31.940: W/System.err(21275):    at com.amazonaws.http.AmazonHttpClient.execute(Unknown Source)
05-25 21:12:31.940: W/System.err(21275):    at com.amazonaws.services.s3.AmazonS3Client.invoke(Unknown Source)
05-25 21:12:31.940: W/System.err(21275):    at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(Unknown Source)
05-25 21:12:31.940: W/System.err(21275):    at com.readystatesoftware.simpl3r.Uploader.start(Uploader.java:180)
05-25 21:12:31.940: W/System.err(21275):    at com.readystatesoftware.simpl3r.example.UploadService.onHandleIntent(UploadService.java:105)
05-25 21:12:31.940: W/System.err(21275):    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
05-25 21:12:31.940: W/System.err(21275):    at android.os.Handler.dispatchMessage(Handler.java:102)
05-25 21:12:31.940: W/System.err(21275):    at android.os.Looper.loop(Looper.java:136)
05-25 21:12:31.940: W/System.err(21275):    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by hboregio** [comment]
Hey, did you ever find a fix for this error? I'm getting the same thing.

**Comment by jaydeepw** [comment]
Nop. Unfortunaltely I did not.

**Comment by hboregio** [comment]
Hey jaydeepw, I actually got it working by using the example code located in the examples folder. I think what was missing from the code was the fact that you have to md5 the filePath before using it as the s3ObjectKey.

**Comment by jaydeepw** [comment]
Alright. Thanks for posting it here. I will try it soon.
In the meanwhile, if you can, please update the doc appropriately.

**Comment by achinverma** [comment]
hi i am getting the same issue , can you you explain a bit more how to solve this error
Status Code: 400, AWS Service: Amazon S3, AWS Request ID: 8E3BB31B5AF13F0D, AWS Error Code: MalformedXML, AWS Error Message:

**Comment by bpr10** [comment]
I am using md5 to hash the filepath to use as the key. Still it shows the same issue. Any ideas ?
